language: java
jdk:
- oraclejdk8
install:
- mvn install
script:
- mvn install
after_success:
- mvn -Pattach-integration-test cobertura:cobertura-integration-test org.eluder.coveralls:coveralls-maven-plugin:4.2.0:report
services:
- postgresql
before_script:
- psql -c 'create database agoravai;' -U postgres